name: all_in_one_image
description: Image utilities for support all image types in one.

homepage: https://github.com/everdev888/all_in_one_image.git
version: 1.0.0

environment:
  sdk: '>=2.12.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_image: ^4.1.5
  flutter_image_compress: ^2.0.3
  flutter_svg: ^2.0.6
  http: ^0.13.6
  image: ^4.0.17
  image_picker: ^0.8.7+5

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
